[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v --strict-markers
base_url = https://storefront:storefront@education-qa.scholastic.ca
markers =
    story1: User story 1 coverage
    story2: User story 2 coverage
