[theme]
primaryColor = "#4f46e5"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#ffffff"
textColor = "#111827"
font = "sans serif"

[server]
runOnSave = true
headless = true
port = 8501

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
